### ISSUE TITLE
Error when marking as watched/unwatched on trakt

### ISSUE THREAD

**Issue by mbouclas** [kodifitzwell/repo#3] opened 2024-04-02 19:44 UTC
Not sure if anyone can help but I get the following error when marking as watched on trakt while using the POV addon. 

```
   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\pov.py", line 8, in <module>
                                                       routing(params)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\modules\router.py", line 123, in routing
                                                       mark_as_watched_unwatched_episode(params)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\caches\watched_cache.py", line 352, in mark_as_watched_unwatched_episode
                                                       elif not trakt_watched_unwatched(action, media_type, tmdb_id, tvdb_id, season, episode): return kodi_utils.notification(32574)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 137, in trakt_watched_unwatched
                                                       success = result[result_key][success_key] > 0
                                                   TypeError: 'NoneType' object is not subscriptable
```

Any input is appreciated

**Comment by kodifitzwell** [comment] 2024-04-02 19:57
the request to trakt returned None/nothing.  where is the rest of the log as there should be some indicator.

any particular movie/season+episode you were trying to mark?  I tested rn and could not reproduce.

**Comment by mbouclas** [comment] 2024-04-02 20:05
What follows is the entire log. I have authorized trakt just before testing it. It happens on 3 different kodi installations (2 pcs and 1 android) on any show/movie

```
2024-04-02 23:03:11.944 T:6064     info <general>: >> trakt error <<: 401 Client Error: Unauthorized for url: https://api.trakt.tv/sync/history
2024-04-02 23:03:11.945 T:6064    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\pov.py", line 8, in <module>
                                                       routing(params)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\modules\router.py", line 123, in routing
                                                       mark_as_watched_unwatched_episode(params)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\caches\watched_cache.py", line 352, in mark_as_watched_unwatched_episode
                                                       elif not trakt_watched_unwatched(action, media_type, tmdb_id, tvdb_id, season, episode): return kodi_utils.notification(32574)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 137, in trakt_watched_unwatched
                                                       success = result[result_key][success_key] > 0
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2024-04-02 23:03:12.129 T:42084    info <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
```

**Comment by mbouclas** [comment] 2024-04-02 20:06
and this is what popped up right after i revoked and re-authorized trakt
```
6.337 T:4372    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: ('Connection aborted.', timeout('The read operation timed out'))
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 790, in urlopen
                                                       response = self._make_request(
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 536, in _make_request
                                                       response = conn.getresponse()
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 461, in getresponse
                                                       httplib_response = super().getresponse()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1348, in getresponse
                                                       response.begin()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 316, in begin
                                                       version, status, reason = self._read_status()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 277, in _read_status
                                                       line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                     File "C:\Program Files\Kodi\system\python\Lib\socket.py", line 669, in readinto
                                                       return self._sock.recv_into(b)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1241, in recv_into
                                                       return self.read(nbytes, buffer)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1099, in read
                                                       return self._sslobj.read(len, buffer)
                                                   socket.timeout: The read operation timed out
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 844, in urlopen
                                                       retries = retries.increment(
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\retry.py", line 470, in increment
                                                       raise reraise(type(error), error, _stacktrace)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\util.py", line 38, in reraise
                                                       raise value.with_traceback(tb)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 790, in urlopen
                                                       response = self._make_request(
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 536, in _make_request
                                                       response = conn.getresponse()
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 461, in getresponse
                                                       httplib_response = super().getresponse()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1348, in getresponse
                                                       response.begin()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 316, in begin
                                                       version, status, reason = self._read_status()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 277, in _read_status
                                                       line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                     File "C:\Program Files\Kodi\system\python\Lib\socket.py", line 669, in readinto
                                                       return self._sock.recv_into(b)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1241, in recv_into
                                                       return self.read(nbytes, buffer)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1099, in read
                                                       return self._sslobj.read(len, buffer)
                                                   urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The read operation timed out'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\pov.py", line 8, in <module>
                                                       routing(params)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\modules\router.py", line 68, in routing
                                                       trakt_auth()
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 647, in trakt_auth
                                                       trakt_sync_activities(force_update=True)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 584, in trakt_sync_activities
                                                       if _compare(latest_episodes['watched_at'], cached_episodes['watched_at']): trakt_indicators_tv()
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 447, in trakt_indicators_tv
                                                       result = get_trakt(url)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 539, in get_trakt
                                                       result = call_trakt(params['path'] % params.get('path_insert', ''), params=params.get('params', {}), data=params.get('data'),
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 34, in call_trakt
                                                       response = _request()
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py", line 27, in _request
                                                       else: resp = session.get(base_url % path, params=params, headers=headers, timeout=timeout)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 602, in get
                                                       return self.request("GET", url, **kwargs)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "C:\Users\mbouc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 501, in send
                                                       raise ConnectionError(err, request=request)
                                                   requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The read operation timed out'))
                                                   -->End of Python script error report<--
```

**Comment by mbouclas** [comment] 2024-04-02 20:32
I've only started using it for a couple weeks now. The first few days it worked without any problems, but since then it's been acting like that. The addon shows i'm authorized on trakt, the official trakt plugin works fine, and other than that there hasn't been any changes on any of the 3 setups. 
As an extra bit of info, i have uninstalled/reinstalled trakt and POV just to be on the safe side. Also, cleared all caches

**Comment by kodifitzwell** [comment] 2024-04-02 20:57
> I've only started using it for a couple weeks now. The first few days it worked without any problems, but since then it's been acting like that.

are you able to browse the My Lists menu, Account Info, Lists, Watchlists and such?

the only real change in the addons trakt coding from March 1 to April 1 was separating api keys between my addons.  but a deauth/auth took care of that.

**Comment by kodifitzwell** [comment] 2024-04-02 21:42
> It's hit or miss on that front.

the addon code doesn't change between, and the auth token shouldn't either.

on windows at least its fairly simple to change the `timeout`.  using a plain text editor like Notepad, find this file:

    C:\Users\mbouc\AppData\Roaming\Kodi\addons\plugin.video.pov\resources\lib\apis\trakt_api.py

near the top you will see `timeout = 3.05`, change it to something like `timeout = 10` and see if that helps.

if not, the only other thing I could do is ask you to install a special zip with some extra extra logging.

**Comment by mbouclas** [comment] 2024-04-02 21:43
thank you for your time and effort. Will try it out

**Comment by kodifitzwell** [comment] 2024-04-10 17:09
is there any update on this issue?  the recent update includes a small bit of more detailed logging.

**Comment by mbouclas** [comment] 2024-04-10 17:26
On the PC, i've increased the timeout to 5 and all good. On the Android devices, it still comes and goes. Need to re-auth every couple of days

**Comment by kodifitzwell** [comment] 2024-04-10 18:22
I'm going to close the issue for now.  can't think of any reason why android would be a problem.  and I guess one last question, is it just trakt auth that needs to be redone every few days or debrids too?

in any case, along with the `>> trakt error <<:...` there should now be two lines below with a bit of more detail for what trakt returns about the error.  if you see anything interesting, lmk.

**Closed** 2024-04-10 18:22 UTC

**Comment by mbouclas** [comment] 2024-04-10 18:23
Just trakt, debrid is solid as a rock,
