### ISSUE TITLE
POV - Error when using "Marked Watched Trakt"

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#6] opened 2024-04-07 16:06 UTC
When attempting to mark a series episode as watched using the context menu item, "Marked Watched Trakt", POV produces an error. 

[Link to log file.](https://paste.kodi.tv/efegalatuk)

I cleared cache in POV, unauthorized, and reauthorized Trakt, and also tried to uninstall POV, then authorizing Trakt, yet the error still happens.

Thanks!

**Comment by kodifitzwell** [comment] 2024-04-07 16:14
I see what the issue is.  thanks for reporting it, will be in the next update.

**Comment by Hemicrusher** [comment] 2024-04-07 19:55
Fixed!

Have a great week!

**Closed** 2024-04-07 21:58 UTC
